# Assignment (Code Challenges)

**1. Develop a python function from scratch that will find the determinants of any $n$ x $n$ matrix.**

In [17]:
def find_det(A):
    assert len(A) == 0 or all(type(row) == list for row in A) and len(A) == len(A[0]), "A should be a square matrix."
    
    n = len(A)
    if   n == 0: return 1.
    elif n == 1: return A[0][0]
    elif n == 2: return A[0][0] * A[1][1] - A[0][1] * A[1][0] 

    det = 0.
    for col, cofactor in enumerate(A[0]):
        minor = [[A[i][j] for j in range(n) if j != col] for i in range(1, n)]
        det += (-1) ** col * cofactor * find_det(minor)

    return det

**2. Develop a python function from scratch that will find both the eigenvectors and eigenvalues of any $n$ x $n$ matrix.**

In [19]:
def find_eigen(A, max_iterations = 50000):
    assert len(A) == 0 or all(type(row) == list for row in A) and len(A) == len(A[0]), "A should be a square matrix."

    n = len(A) 
    if n == 0: return [], []
    if n == 1: return [A[0][0]], [[1.]]

    eigenvectors = []
    eigenvalues = []

    for _ in range(n):
        eigvec = [random.random() for _ in range(n)]
        norm_eigvec = sum(a ** 2 for a in eigvec) ** 0.5
        eigvec = [a / norm_eigvec for a in eigvec]

        for _ in range(max_iterations):
            tf_eigvec = [sum(a * b for a, b in zip(row, eigvec)) for row in A]
            
            norm_tf = sum(a ** 2 for a in tf_eigvec) ** 0.5
            eigvec = [a / norm_tf for a in tf_eigvec]
            
        eigval = sum(a * b for a, b in zip(tf_eigvec, eigvec))
        eigenvalues.append(eigval)
        eigenvectors.append(eigvec)

        eigenval_outer_product = [[a * b for b in eigvec] for a in tf_eigvec]
        A = [[A[i][j] - eigenval_outer_product[i][j] for j in range(n)] for i in range(n)]

    return eigenvalues, [list(row) for row in zip(*eigenvectors)]

**3. Test your functions from a randomly generated $n$ x $n$ matrix.**

**Determinant**

In [20]:
import numpy as np
import random

In [21]:
A = np.random.random((8, 8)).astype("float64") * 5

custom_det = find_det(A.tolist())
numpy_det = np.linalg.det(A)

print("Matrix:", A, sep="\n")
print("\nFROM CUSTOM DETERMINANT FUNCTION:", custom_det, sep="\n")
print("\nNUMPY DETERMINANT:", numpy_det, sep="\n")

Matrix:
[[1.18004501 3.17744756 1.4612134  4.83640394 4.28373455 0.42034037
  2.99884972 1.31571397]
 [3.89051567 2.97937012 1.17666241 0.63053113 2.27305108 2.75346586
  2.23784435 3.02408488]
 [1.26527115 0.90390941 0.95739805 0.13032186 2.14514845 3.07664784
  0.08472566 4.80935437]
 [0.42824157 2.17346761 4.29024295 1.12307309 1.97700511 3.67959663
  2.36793295 0.20093611]
 [4.39794302 0.90246019 1.42641402 0.90447575 0.13881159 2.07283436
  2.78235829 1.18861262]
 [4.73342017 3.60044659 3.81446664 1.66419479 1.34361516 4.00081554
  4.82542217 1.54235552]
 [2.42384965 3.3873768  4.78499894 0.74663721 4.25175042 4.83519721
  3.14149412 2.24940314]
 [0.79235157 1.20082855 1.86497454 4.38929937 3.96658369 2.04410286
  2.43098578 2.11071699]]

FROM CUSTOM DETERMINANT FUNCTION:
704.4832289988295

NUMPY DETERMINANT:
704.483228998828


**Eigenvalue**

In [22]:
A = np.random.random((3, 3)).astype("float64") * 5

np_ev, np_evl = np.linalg.eig(A)
m_ev, m_evl = find_eigen(A.tolist())
m_ev, m_evl = np.array(m_ev), np.array(m_evl)

print("Matrix:", A, sep="\n")
print("\nFROM CUSTOM EIGEN FUNCTION:", m_ev, m_evl, sep="\n")
print("\nFROM NUMPY EIGEN:", np_ev, np_evl, sep="\n")

Matrix:
[[1.52042845 2.14694127 1.92231935]
 [3.82717183 1.74435655 0.54562785]
 [3.71989452 0.56152641 2.69447952]]

FROM CUSTOM EIGEN FUNCTION:
[6.13108481 1.86882712 3.73765424]
[[ 0.52557245  0.09359571 -0.09359571]
 [ 0.54027261 -0.72113085  0.72113085]
 [ 0.6571751  -0.68644748  0.68644748]]

FROM NUMPY EIGEN:
[ 6.13108481 -1.86882712  1.69700683]
[[-0.52557245 -0.64593402 -0.09687837]
 [-0.54027261  0.61612355 -0.66833215]
 [-0.6571751   0.45073385  0.73752743]]
